stages:
    - build
    - test
stage1:
 stage: build
 tags:
     - shell_1
 script:
     - mvn clean install
     - pwd
     - whoami
     - mkdir demo1
     - echo "do your build here"
 artifacts:
      paths: 
          - target/*.war

sast:
  stage: test
  tags:
    - docker
  artifacts:
    name: sast
    paths:
      - gl-sast-report.json
    reports:
      sast: gl-sast-report.json

include:
   - template: Security/SAST.gitlab-ci.yml
   - template: Code-Quality.gitlab-ci.yml
   - template: Jobs/Secret-Detection.gitlab-ci.yml

code_quality:
  stage: test
  tags:
    - docker
  artifacts:
    name: Code
    paths:
      - gl-code-quality-report.json
    reports:
      codequality: gl-code-quality-report.json
  when: always

secret_detection:
  stage: test
  tags:
    - docker
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"
  artifacts:
    paths:
      - gl-secret_detection-report.json

 


# deploy:
#   stage: deploy
#   tags:
#   - shell_1
#   environment: Production
#     # - portalshell
#   script:
# #    - cp path/to/your/war/file.war /path/to/tomcat/webapps/
#     - cp -r target/*.war /opt/tomcat/webapps





