stages:
    - build
    - test
stage1:
 stage: build
 tags:
     - shell_1
 script:
     - mvn clean install
     - pwd
     - whoami
     - mkdir demo1
     - echo "do your build here"
 artifacts:
      paths: 
          - target/*.war

sast:
  stage: test
  tags:
    - docker_runner
  # # artifacts:
  #   name: sast
  #   paths:
  #     - gl-sast-report.json
  #   reports:
  #     sast: gl-sast-report.json

include:
   - template: Security/SAST.gitlab-ci.yml


# deploy:
#   stage: deploy
#   tags:
#   - shell_1
#   environment: Production
#     # - portalshell
#   script:
# #    - cp path/to/your/war/file.war /path/to/tomcat/webapps/
#     - cp -r target/*.war /opt/tomcat/webapps



