stages:
    - build
    - deploy
stage1:
 stage: build
 tags:
     - shell_1
 script:
     - mvn clean install
     - pwd
     - whoami
     - mkdir demo1
     - echo "do your build here"
 artifacts:
      paths: 
          - target/*.war

deploy:
  stage: deploy
  tags:
  - shell_1
  environment: Production
    # - portalshell
  script:
#    - cp path/to/your/war/file.war /path/to/tomcat/webapps/
    - cp -r target/*.war /opt/tomcat/webapps



