stages:
    - build
    - test
stage1:
 stage: build
 tags:
     - shell_1
 script:
     - mvn clean install
     - pwd
     - whoami
     - echo "do your build here"
 artifacts:
      paths: 
          - src/target/*.war

