stages:
    - build
    - test
stage1:
 stage: build
 tags:
     - shell_1
 script:
     - mvn clean install
     - pwd
     - whoami
     - mkdir demo1
     - echo "do your build here"
 artifacts:
      paths: 
          - target/*.war

sast:
  stage: test
  tags:
    - docker
  artifacts:
  
    paths:
      - gl-sast-report.html
    reports:
      sast: gl-sast-report.html

include:
   - template: Security/SAST.gitlab-ci.yml
   - template: Code-Quality.gitlab-ci.yml

code_quality:
  stage: test
  tags:
    - docker
  artifacts:
    paths:
      - gl-code-quality-report.json
    reports:
      codequality: gl-code-quality-report.json
  when: always
 


# deploy:
#   stage: deploy
#   tags:
#   - shell_1
#   environment: Production
#     # - portalshell
#   script:
# #    - cp path/to/your/war/file.war /path/to/tomcat/webapps/
#     - cp -r target/*.war /opt/tomcat/webapps



